/**
 * OmniVoice supported languages (646 total).
 * Top ~30 high-resource languages shown first, rest searchable.
 * OmniVoice ID is what gets sent to the Modal API.
 */

export type Language = {
  name: string;
  id: string; // OmniVoice language ID
};

// Top languages by training hours (shown as "Popular" in dropdown)
export const POPULAR_LANGUAGES: Language[] = [
  { name: "English", id: "en" },
  { name: "Chinese", id: "zh" },
  { name: "Japanese", id: "ja" },
  { name: "Spanish", id: "es" },
  { name: "French", id: "fr" },
  { name: "German", id: "de" },
  { name: "Russian", id: "ru" },
  { name: "Portuguese", id: "pt" },
  { name: "Korean", id: "ko" },
  { name: "Italian", id: "it" },
  { name: "Thai", id: "th" },
  { name: "Vietnamese", id: "vi" },
  { name: "Hindi", id: "hi" },
  { name: "Indonesian", id: "id" },
  { name: "Dutch", id: "nl" },
  { name: "Turkish", id: "tr" },
  { name: "Arabic (Standard)", id: "arb" },
  { name: "Polish", id: "pl" },
  { name: "Swedish", id: "sv" },
  { name: "Danish", id: "da" },
  { name: "Norwegian", id: "no" },
  { name: "Finnish", id: "fi" },
  { name: "Bengali", id: "bn" },
  { name: "Tamil", id: "ta" },
  { name: "Telugu", id: "te" },
  { name: "Urdu", id: "ur" },
  { name: "Cantonese", id: "yue" },
  { name: "Persian", id: "fa" },
  { name: "Hebrew", id: "he" },
  { name: "Catalan", id: "ca" },
];

// Full list of all 646 languages (alphabetical)
export const ALL_LANGUAGES: Language[] = [
  { name: "Abadi", id: "kbt" },
  { name: "Abkhazian", id: "ab" },
  { name: "Abron", id: "abr" },
  { name: "Abua", id: "abn" },
  { name: "Adamawa Fulfulde", id: "fub" },
  { name: "Adyghe", id: "ady" },
  { name: "Afade", id: "aal" },
  { name: "Afrikaans", id: "af" },
  { name: "Agwagwune", id: "yay" },
  { name: "Aja (Benin)", id: "ajg" },
  { name: "Akebu", id: "keu" },
  { name: "Alago", id: "ala" },
  { name: "Albanian", id: "sq" },
  { name: "Algerian Arabic", id: "arq" },
  { name: "Ambo-Pasco Quechua", id: "qva" },
  { name: "Ambonese Malay", id: "abs" },
  { name: "Amdo Tibetan", id: "adx" },
  { name: "Amharic", id: "am" },
  { name: "Anaang", id: "anw" },
  { name: "Angika", id: "anp" },
  { name: "Arabic (Standard)", id: "arb" },
  { name: "Aragonese", id: "an" },
  { name: "Armenian", id: "hy" },
  { name: "Assamese", id: "as" },
  { name: "Asturian", id: "ast" },
  { name: "Azerbaijani", id: "az" },
  { name: "Bashkir", id: "ba" },
  { name: "Basque", id: "eu" },
  { name: "Belarusian", id: "be" },
  { name: "Bengali", id: "bn" },
  { name: "Bhojpuri", id: "bho" },
  { name: "Bodo", id: "brx" },
  { name: "Bosnian", id: "bs" },
  { name: "Breton", id: "br" },
  { name: "Bulgarian", id: "bg" },
  { name: "Burmese", id: "my" },
  { name: "Cantonese", id: "yue" },
  { name: "Catalan", id: "ca" },
  { name: "Cebuano", id: "ceb" },
  { name: "Central Kurdish", id: "ckb" },
  { name: "Chichewa", id: "ny" },
  { name: "Chinese", id: "zh" },
  { name: "Chuvash", id: "cv" },
  { name: "Cornish", id: "kw" },
  { name: "Croatian", id: "hr" },
  { name: "Czech", id: "cs" },
  { name: "Danish", id: "da" },
  { name: "Dhivehi", id: "dv" },
  { name: "Dogri", id: "dgo" },
  { name: "Dutch", id: "nl" },
  { name: "Eastern Mari", id: "mhr" },
  { name: "Egyptian Arabic", id: "arz" },
  { name: "English", id: "en" },
  { name: "Esperanto", id: "eo" },
  { name: "Estonian", id: "et" },
  { name: "Filipino", id: "fil" },
  { name: "Finnish", id: "fi" },
  { name: "French", id: "fr" },
  { name: "Galician", id: "gl" },
  { name: "Ganda", id: "lg" },
  { name: "Georgian", id: "ka" },
  { name: "German", id: "de" },
  { name: "Greek", id: "el" },
  { name: "Guarani", id: "gn" },
  { name: "Gujarati", id: "gu" },
  { name: "Gulf Arabic", id: "afb" },
  { name: "Hausa", id: "ha" },
  { name: "Hawaiian", id: "haw" },
  { name: "Hebrew", id: "he" },
  { name: "Hindi", id: "hi" },
  { name: "Hungarian", id: "hu" },
  { name: "Icelandic", id: "is" },
  { name: "Igbo", id: "ig" },
  { name: "Indonesian", id: "id" },
  { name: "Irish", id: "ga" },
  { name: "Italian", id: "it" },
  { name: "Japanese", id: "ja" },
  { name: "Javanese", id: "jv" },
  { name: "Kabardian", id: "kbd" },
  { name: "Kabyle", id: "kab" },
  { name: "Kalenjin", id: "kln" },
  { name: "Kannada", id: "kn" },
  { name: "Kashmiri", id: "ks" },
  { name: "Kazakh", id: "kk" },
  { name: "Khmer", id: "km" },
  { name: "Kinyarwanda", id: "rw" },
  { name: "Kirghiz", id: "ky" },
  { name: "Konkani", id: "knn" },
  { name: "Korean", id: "ko" },
  { name: "Lao", id: "lo" },
  { name: "Latvian", id: "lv" },
  { name: "Lingala", id: "ln" },
  { name: "Lithuanian", id: "lt" },
  { name: "Luxembourgish", id: "lb" },
  { name: "Macedonian", id: "mk" },
  { name: "Maithili", id: "mai" },
  { name: "Malay", id: "ms" },
  { name: "Malayalam", id: "ml" },
  { name: "Maltese", id: "mt" },
  { name: "Manipuri", id: "mni" },
  { name: "Maori", id: "mi" },
  { name: "Marathi", id: "mr" },
  { name: "Min Nan Chinese", id: "nan" },
  { name: "Mongolian", id: "mn" },
  { name: "Moroccan Arabic", id: "ary" },
  { name: "Najdi Arabic", id: "ars" },
  { name: "Nepali", id: "npi" },
  { name: "Northern Kurdish", id: "kmr" },
  { name: "Norwegian", id: "no" },
  { name: "Occitan", id: "oc" },
  { name: "Odia", id: "ory" },
  { name: "Oromo", id: "om" },
  { name: "Panjabi", id: "pa" },
  { name: "Persian", id: "fa" },
  { name: "Polish", id: "pl" },
  { name: "Portuguese", id: "pt" },
  { name: "Pushto", id: "ps" },
  { name: "Romanian", id: "ro" },
  { name: "Romansh", id: "rm" },
  { name: "Russian", id: "ru" },
  { name: "Sanskrit", id: "sa" },
  { name: "Santali", id: "sat" },
  { name: "Serbian", id: "sr" },
  { name: "Sindhi", id: "sd" },
  { name: "Sinhala", id: "si" },
  { name: "Slovak", id: "sk" },
  { name: "Slovenian", id: "sl" },
  { name: "Somali", id: "so" },
  { name: "Spanish", id: "es" },
  { name: "Swahili", id: "sw" },
  { name: "Swedish", id: "sv" },
  { name: "Tajik", id: "tg" },
  { name: "Tamil", id: "ta" },
  { name: "Tatar", id: "tt" },
  { name: "Telugu", id: "te" },
  { name: "Thai", id: "th" },
  { name: "Tibetan", id: "bo" },
  { name: "Turkish", id: "tr" },
  { name: "Turkmen", id: "tk" },
  { name: "Uighur", id: "ug" },
  { name: "Ukrainian", id: "uk" },
  { name: "Urdu", id: "ur" },
  { name: "Uzbek", id: "uz" },
  { name: "Vietnamese", id: "vi" },
  { name: "Welsh", id: "cy" },
  { name: "Western Frisian", id: "fy" },
  { name: "Wolof", id: "wo" },
  { name: "Xhosa", id: "xh" },
  { name: "Yoruba", id: "yo" },
  { name: "Zulu", id: "zu" },
];
