# ─────────────────────────────────────────────────────────────────────────────
# WHY THIS FILE EXISTS:
# This is a Mako template (.mako) that Alembic uses to GENERATE new migration
# files when you run `alembic revision` or `alembic revision --autogenerate`.
#
# CONCEPT: Mako is a Python template engine (like Jinja2 but simpler).
# Alembic chose Mako because it was already a SQLAlchemy ecosystem dependency.
# The ${variables} below get replaced with actual values when generating a
# new migration file.
#
# WHY we customize this template:
#   - We add docstrings explaining the migration
#   - We ensure consistent imports across all generated files
#   - The default template is bare-bones; ours matches our annotation style
# ─────────────────────────────────────────────────────────────────────────────

"""Add call_analysis table for VoiceInsight

Revision ID: 1e1de1742a14
Revises: c7d8e9f0a1b2
Create Date: 2026-08-15 03:30:53.150631+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# ── Alembic revision identifiers (used by the migration tracker) ──
revision: str = '1e1de1742a14'
down_revision: Union[str, None] = 'c7d8e9f0a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration — move the DB schema FORWARD."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'TRANSCRIBING', 'EXTRACTING', 'COMPLETED', 'FAILED', name='analysisstatus'), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('audio_url', sa.String(length=1024), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('gladia_job_id', sa.String(length=255), nullable=True),
    sa.Column('transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('intelligence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_analysis_gladia_job_id'), 'call_analysis', ['gladia_job_id'], unique=False)
    op.create_index('ix_call_analysis_search_vector', 'call_analysis', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_call_analysis_status'), 'call_analysis', ['status'], unique=False)
    op.create_index(op.f('ix_call_analysis_user_id'), 'call_analysis', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration — move the DB schema BACKWARD."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_analysis_user_id'), table_name='call_analysis')
    op.drop_index(op.f('ix_call_analysis_status'), table_name='call_analysis')
    op.drop_index('ix_call_analysis_search_vector', table_name='call_analysis', postgresql_using='gin')
    op.drop_index(op.f('ix_call_analysis_gladia_job_id'), table_name='call_analysis')
    op.drop_table('call_analysis')
    # ### end Alembic commands ###
