# ─────────────────────────────────────────────────────────────────────────────
# WHY THIS FILE EXISTS:
# This is a Mako template (.mako) that Alembic uses to GENERATE new migration
# files when you run `alembic revision` or `alembic revision --autogenerate`.
#
# CONCEPT: Mako is a Python template engine (like Jinja2 but simpler).
# Alembic chose Mako because it was already a SQLAlchemy ecosystem dependency.
# The ${variables} below get replaced with actual values when generating a
# new migration file.
#
# WHY we customize this template:
#   - We add docstrings explaining the migration
#   - We ensure consistent imports across all generated files
#   - The default template is bare-bones; ours matches our annotation style
# ─────────────────────────────────────────────────────────────────────────────

"""initial_schema

Revision ID: 2aea2244f4ba
Revises: 
Create Date: 2026-06-05 10:56:01.449475+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# ── Alembic revision identifiers (used by the migration tracker) ──
revision: str = '2aea2244f4ba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration — move the DB schema FORWARD."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clerk_user_id', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('plan_type', sa.Text(), server_default='free', nullable=False),
    sa.Column('credit_balance', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("plan_type IN ('free', 'premium')", name='chk_plan_type'),
    sa.CheckConstraint('credit_balance >= 0', name='chk_credit_balance_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    op.create_table('uploaded_videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('r2_key', sa.Text(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'processed', 'expired', name='uploaded_video_status'), server_default='uploaded', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_videos_user_id'), 'uploaded_videos', ['user_id'], unique=False)
    op.create_table('user_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.Enum('voice_sample', 'instrumental', 'reference_video', name='asset_type'), nullable=False),
    sa.Column('r2_key', sa.Text(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('r2_key')
    )
    op.create_index(op.f('ix_user_assets_user_id'), 'user_assets', ['user_id'], unique=False)
    op.create_table('clone_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('voice_asset_id', sa.UUID(), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('source_language', sa.Text(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('external_job_id', sa.Text(), nullable=True),
    sa.Column('provider_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('queued', 'processing', 'succeeded', 'failed', name='clone_job_status'), server_default='queued', nullable=False),
    sa.Column('clone_stage', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('output_r2_key', sa.Text(), nullable=True),
    sa.Column('output_duration_ms', sa.Integer(), nullable=True),
    sa.Column('credit_cost', sa.Integer(), nullable=True),
    sa.Column('credits_deducted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voice_asset_id'], ['user_assets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clone_jobs_user_id'), 'clone_jobs', ['user_id'], unique=False)
    op.create_table('dub_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_video_id', sa.UUID(), nullable=True),
    sa.Column('voice_asset_id', sa.UUID(), nullable=True),
    sa.Column('source_language', sa.Text(), nullable=False),
    sa.Column('target_language', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('model_name', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'transcribing', 'translating', 'cloning', 'assembling', 'completed', 'failed', name='dub_job_status'), server_default='queued', nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('credit_cost', sa.Integer(), nullable=True),
    sa.Column('credits_deducted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_video_id'], ['uploaded_videos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['voice_asset_id'], ['user_assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dub_jobs_user_id'), 'dub_jobs', ['user_id'], unique=False)
    op.create_table('credit_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dub_job_id', sa.UUID(), nullable=True),
    sa.Column('clone_job_id', sa.UUID(), nullable=True),
    sa.Column('txn_type', sa.Enum('top_up', 'deduction', 'refund', name='txn_type'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('NOT (dub_job_id IS NOT NULL AND clone_job_id IS NOT NULL)', name='chk_one_job_ref'),
    sa.CheckConstraint('amount > 0', name='chk_transaction_amount_positive'),
    sa.ForeignKeyConstraint(['clone_job_id'], ['clone_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dub_job_id'], ['dub_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_transactions_user_id'), 'credit_transactions', ['user_id'], unique=False)
    op.create_table('final_dubs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dub_job_id', sa.UUID(), nullable=False),
    sa.Column('r2_key', sa.Text(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dub_job_id'], ['dub_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dub_job_id'),
    sa.UniqueConstraint('r2_key')
    )
    op.create_table('history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('clone_job_id', sa.UUID(), nullable=True),
    sa.Column('dub_job_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clone_job_id'], ['clone_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dub_job_id'], ['dub_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_user_id'), 'history', ['user_id'], unique=False)
    op.create_table('transcription_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dub_job_id', sa.UUID(), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=False),
    sa.Column('start_sec', sa.Float(), nullable=False),
    sa.Column('end_sec', sa.Float(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('translated_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('segment_index >= 0', name='chk_segment_index_positive'),
    sa.CheckConstraint('start_sec >= 0 AND end_sec > start_sec', name='chk_segment_timing'),
    sa.ForeignKeyConstraint(['dub_job_id'], ['dub_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dub_job_id', 'segment_index', name='uq_ts_job_segment')
    )
    op.create_index(op.f('ix_transcription_segments_dub_job_id'), 'transcription_segments', ['dub_job_id'], unique=False)
    op.create_table('dub_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transcription_segment_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('model_name', sa.Text(), nullable=True),
    sa.Column('external_job_id', sa.Text(), nullable=True),
    sa.Column('provider_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('r2_key', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='dub_segment_status'), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transcription_segment_id'], ['transcription_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transcription_segment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration — move the DB schema BACKWARD."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dub_segments')
    op.drop_index(op.f('ix_transcription_segments_dub_job_id'), table_name='transcription_segments')
    op.drop_table('transcription_segments')
    op.drop_index(op.f('ix_history_user_id'), table_name='history')
    op.drop_table('history')
    op.drop_table('final_dubs')
    op.drop_index(op.f('ix_credit_transactions_user_id'), table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_index(op.f('ix_dub_jobs_user_id'), table_name='dub_jobs')
    op.drop_table('dub_jobs')
    op.drop_index(op.f('ix_clone_jobs_user_id'), table_name='clone_jobs')
    op.drop_table('clone_jobs')
    op.drop_index(op.f('ix_user_assets_user_id'), table_name='user_assets')
    op.drop_table('user_assets')
    op.drop_index(op.f('ix_uploaded_videos_user_id'), table_name='uploaded_videos')
    op.drop_table('uploaded_videos')
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
