# ─────────────────────────────────────────────────────────────────────────────
# WHY THIS FILE EXISTS:
# This is a Mako template (.mako) that Alembic uses to GENERATE new migration
# files when you run `alembic revision` or `alembic revision --autogenerate`.
#
# CONCEPT: Mako is a Python template engine (like Jinja2 but simpler).
# Alembic chose Mako because it was already a SQLAlchemy ecosystem dependency.
# The ${variables} below get replaced with actual values when generating a
# new migration file.
#
# WHY we customize this template:
#   - We add docstrings explaining the migration
#   - We ensure consistent imports across all generated files
#   - The default template is bare-bones; ours matches our annotation style
# ─────────────────────────────────────────────────────────────────────────────

"""add_dubbing_pipeline_columns

Revision ID: 58c91234eaf7
Revises: 9607d0c5c21c
Create Date: 2026-06-11 07:47:52.623643+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# ── Alembic revision identifiers (used by the migration tracker) ──
revision: str = '58c91234eaf7'
down_revision: Union[str, None] = '9607d0c5c21c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration — move the DB schema FORWARD."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dub_jobs', sa.Column('full_audio_r2_key', sa.Text(), nullable=True))
    op.add_column('dub_jobs', sa.Column('vocal_r2_key', sa.Text(), nullable=True))
    op.add_column('dub_jobs', sa.Column('instrumental_r2_key', sa.Text(), nullable=True))
    op.add_column('dub_jobs', sa.Column('gladia_job_id', sa.Text(), nullable=True))
    op.add_column('dub_jobs', sa.Column('translation_provider', sa.Text(), nullable=True))
    op.add_column('dub_jobs', sa.Column('current_phase', sa.Text(), nullable=True))
    op.add_column('dub_jobs', sa.Column('progress_pct', sa.Integer(), server_default='0', nullable=True))
    op.add_column('dub_jobs', sa.Column('progress_message', sa.Text(), nullable=True))
    op.add_column('dub_segments', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('dub_segments', sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('transcription_segments', sa.Column('speaker_id', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration — move the DB schema BACKWARD."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcription_segments', 'speaker_id')
    op.drop_column('dub_segments', 'retry_count')
    op.drop_column('dub_segments', 'error_message')
    op.drop_column('dub_jobs', 'progress_message')
    op.drop_column('dub_jobs', 'progress_pct')
    op.drop_column('dub_jobs', 'current_phase')
    op.drop_column('dub_jobs', 'translation_provider')
    op.drop_column('dub_jobs', 'gladia_job_id')
    op.drop_column('dub_jobs', 'instrumental_r2_key')
    op.drop_column('dub_jobs', 'vocal_r2_key')
    op.drop_column('dub_jobs', 'full_audio_r2_key')
    # ### end Alembic commands ###
