# ─────────────────────────────────────────────────────────────────────────────
# WHY THIS FILE EXISTS:
# This is a Mako template (.mako) that Alembic uses to GENERATE new migration
# files when you run `alembic revision` or `alembic revision --autogenerate`.
#
# CONCEPT: Mako is a Python template engine (like Jinja2 but simpler).
# Alembic chose Mako because it was already a SQLAlchemy ecosystem dependency.
# The ${variables} below get replaced with actual values when generating a
# new migration file.
#
# WHY we customize this template:
#   - We add docstrings explaining the migration
#   - We ensure consistent imports across all generated files
#   - The default template is bare-bones; ours matches our annotation style
# ─────────────────────────────────────────────────────────────────────────────

"""drop_dubbing_tables

Revision ID: 6852d130554b
Revises: f5a8b2c3d4e5
Create Date: 2026-06-23 12:30:44.111751+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# ── Alembic revision identifiers (used by the migration tracker) ──
revision: str = '6852d130554b'
down_revision: Union[str, None] = 'f5a8b2c3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration — move the DB schema FORWARD."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dub_segments')
    op.drop_index(op.f('ix_transcription_segments_dub_job_id'), table_name='transcription_segments')
    op.drop_table('transcription_segments')
    op.drop_table('final_dubs')
    op.drop_constraint(op.f('credit_transactions_dub_job_id_fkey'), 'credit_transactions', type_='foreignkey')
    op.drop_column('credit_transactions', 'dub_job_id')
    op.drop_constraint(op.f('history_dub_job_id_fkey'), 'history', type_='foreignkey')
    op.drop_column('history', 'dub_job_id')
    op.drop_index(op.f('ix_dub_jobs_user_id'), table_name='dub_jobs')
    op.drop_table('dub_jobs')
    op.drop_index(op.f('ix_uploaded_videos_user_id'), table_name='uploaded_videos')
    op.drop_table('uploaded_videos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration — move the DB schema BACKWARD."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('dub_job_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('history_dub_job_id_fkey'), 'history', 'dub_jobs', ['dub_job_id'], ['id'], ondelete='SET NULL')
    op.add_column('credit_transactions', sa.Column('dub_job_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('credit_transactions_dub_job_id_fkey'), 'credit_transactions', 'dub_jobs', ['dub_job_id'], ['id'], ondelete='SET NULL')
    op.create_table('final_dubs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('dub_job_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('r2_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dub_job_id'], ['dub_jobs.id'], name=op.f('final_dubs_dub_job_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('final_dubs_pkey')),
    sa.UniqueConstraint('dub_job_id', name=op.f('final_dubs_dub_job_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('r2_key', name=op.f('final_dubs_r2_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('dub_jobs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uploaded_video_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('voice_asset_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('source_language', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('target_language', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('model_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('queued', 'uploading', 'extracting_audio', 'separating', 'transcribing', 'translating', 'cloning', 'assembling', 'completed', 'failed', name='dub_job_status'), server_default=sa.text("'queued'::dub_job_status"), autoincrement=False, nullable=False),
    sa.Column('failure_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('credit_cost', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('credits_deducted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('full_audio_r2_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vocal_r2_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('instrumental_r2_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gladia_job_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('translation_provider', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('current_phase', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('progress_pct', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('progress_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['uploaded_video_id'], ['uploaded_videos.id'], name=op.f('dub_jobs_uploaded_video_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('dub_jobs_user_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['voice_asset_id'], ['user_assets.id'], name=op.f('dub_jobs_voice_asset_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('dub_jobs_pkey'))
    )
    op.create_index(op.f('ix_dub_jobs_user_id'), 'dub_jobs', ['user_id'], unique=False)
    op.create_table('uploaded_videos',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('r2_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('uploaded', 'processing', 'processed', 'expired', name='uploaded_video_status'), server_default=sa.text("'uploaded'::uploaded_video_status"), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('uploaded_videos_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('uploaded_videos_pkey'))
    )
    op.create_index(op.f('ix_uploaded_videos_user_id'), 'uploaded_videos', ['user_id'], unique=False)
    op.create_table('dub_segments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('transcription_segment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('model_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('external_job_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('provider_meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('r2_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='dub_segment_status'), server_default=sa.text("'pending'::dub_segment_status"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['transcription_segment_id'], ['transcription_segments.id'], name=op.f('dub_segments_transcription_segment_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('dub_segments_pkey')),
    sa.UniqueConstraint('transcription_segment_id', name=op.f('dub_segments_transcription_segment_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('transcription_segments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('dub_job_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('segment_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_sec', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('end_sec', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('original_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('translated_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('speaker_id', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.CheckConstraint('segment_index >= 0', name=op.f('chk_segment_index_positive')),
    sa.CheckConstraint('start_sec >= 0::double precision AND end_sec > start_sec', name=op.f('chk_segment_timing')),
    sa.ForeignKeyConstraint(['dub_job_id'], ['dub_jobs.id'], name=op.f('transcription_segments_dub_job_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('transcription_segments_pkey')),
    sa.UniqueConstraint('dub_job_id', 'segment_index', name=op.f('uq_ts_job_segment'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_transcription_segments_dub_job_id'), 'transcription_segments', ['dub_job_id'], unique=False)
    # ### end Alembic commands ###
