"""add_email_events_table

Revision ID: 8ed9661d4d03
Revises: g1h2i3j4k5l6
Create Date: 2026-09-09 02:02:32.270257+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# ── Alembic revision identifiers ──
revision: str = '8ed9661d4d03'
down_revision: Union[str, None] = 'g1h2i3j4k5l6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration — create email_events table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email_type', sa.Text(), nullable=False),
    sa.Column('campaign_id', sa.Text(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_events_user_id'), 'email_events', ['user_id'], unique=False)
    op.create_index('ix_email_events_user_type', 'email_events', ['user_id', 'email_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration — drop email_events table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_email_events_user_type', table_name='email_events')
    op.drop_index(op.f('ix_email_events_user_id'), table_name='email_events')
    op.drop_table('email_events')
    # ### end Alembic commands ###
