# ─────────────────────────────────────────────────────────────────────────────
# WHY THIS FILE EXISTS:
# This is a Mako template (.mako) that Alembic uses to GENERATE new migration
# files when you run `alembic revision` or `alembic revision --autogenerate`.
#
# CONCEPT: Mako is a Python template engine (like Jinja2 but simpler).
# Alembic chose Mako because it was already a SQLAlchemy ecosystem dependency.
# The ${variables} below get replaced with actual values when generating a
# new migration file.
#
# WHY we customize this template:
#   - We add docstrings explaining the migration
#   - We ensure consistent imports across all generated files
#   - The default template is bare-bones; ours matches our annotation style
# ─────────────────────────────────────────────────────────────────────────────

"""add_target_language_to_clone_jobs

Revision ID: 9607d0c5c21c
Revises: 2aea2244f4ba
Create Date: 2026-06-07 15:46:08.973837+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# ── Alembic revision identifiers (used by the migration tracker) ──
revision: str = '9607d0c5c21c'
down_revision: Union[str, None] = '2aea2244f4ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration — move the DB schema FORWARD."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clone_jobs', sa.Column('target_language', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration — move the DB schema BACKWARD."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clone_jobs', 'target_language')
    # ### end Alembic commands ###
