# ─────────────────────────────────────────────────────────────────────────────
# WHY THIS FILE EXISTS:
# This is a Mako template (.mako) that Alembic uses to GENERATE new migration
# files when you run `alembic revision` or `alembic revision --autogenerate`.
#
# CONCEPT: Mako is a Python template engine (like Jinja2 but simpler).
# Alembic chose Mako because it was already a SQLAlchemy ecosystem dependency.
# The ${variables} below get replaced with actual values when generating a
# new migration file.
#
# WHY we customize this template:
#   - We add docstrings explaining the migration
#   - We ensure consistent imports across all generated files
#   - The default template is bare-bones; ours matches our annotation style
# ─────────────────────────────────────────────────────────────────────────────

"""add saved_voices table

Revision ID: d1ae0fce7831
Revises: a1b2c3d4e5f6
Create Date: 2026-06-21 03:23:29.581284+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# ── Alembic revision identifiers (used by the migration tracker) ──
revision: str = 'd1ae0fce7831'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration — move the DB schema FORWARD."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_voices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('voice_type', sa.Enum('custom', 'preset', name='voice_type'), server_default='custom', nullable=False),
    sa.Column('r2_key', sa.Text(), nullable=False),
    sa.Column('language', sa.Text(), server_default='en', nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('is_preset', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_voices_user_id'), 'saved_voices', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration — move the DB schema BACKWARD."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_voices_user_id'), table_name='saved_voices')
    op.drop_table('saved_voices')
    # ### end Alembic commands ###
